POST https://localhost:8443/api/seguridad/login
Content-Type: application/json

{
  "username": "root",
  "password": "12345"
}

> {%
     client.global.set("auth_token", response.headers.valueOf("Authorization"));
     client.log("LOG "+response.headers.valueOf("Authorization"));
%}
###

GET https://localhost:8443/api/recursos
Accept: application/json
Content-Type: */*
#Content-Type: */*
###


POST https://localhost:8443/api/recursos
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "id": null,
  "nombre": "Nombre recurso",
  "url": "urlRecurso",
  "publico": true
}

###

GET https://localhost:8443/api/recursos
Accept: application/json
Content-Type: */*
Authorization: {{auth_token}}
###

POST https://localhost:8443/api/recursos
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "nombre": "Nombre recurso",
  "url": "urlRecurso",
  "publico": true
}

###

POST https://localhost:8443/api/recursos
Accept: application/json
Content-Type: application/json

{
  "id": "6028cd33-9fd7-4910-b13a-9a9487aaa1a8",
  "nombre": "Nombre recurso",
  "url": "urlRecurso",
  "publico": true
}

###

PUT https://localhost:8443/api/recursos/6028cd33-9fd7-4910-b13a-9a9487aaa1a8
Accept: application/json
Content-Type: application/json

{
  "id": "6028cd33-9fd7-4910-b13a-9a9487aaa1a8",
  "nombre": "Nombre recurso",
  "url": "urlRecurso",
  "publico": false
}

###

DELETE https://localhost:8443/api/recursos/6028cd33-9fd7-4910-b13a-9a9487aaa1a8
Accept: application/json
Content-Type: application/json
