POST https://localhost:8443/api/seguridad/login
Content-Type: application/json

{
  "username": "root",
  "password": "12345"
}

> {%
     client.global.set("auth_token", response.headers.valueOf("Authorization"));
     client.log("LOG "+response.headers.valueOf("Authorization"));
%}
###

GET https://localhost:8443/api/usuarios
Accept: application/json
#Content-Type: */*
###


POST https://localhost:8443/api/usuarios
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "nombreUsuario": "prueba",
  "clave": "12345",
  "nombre": "Usuario de Prueba",
  "email": "usuario@test.com",
  "pasoActual": null,
  "estado": "ACTIVO",
  "intentos": 0,
  "roles": [],
  "id": "2f119690-96fe-4336-aeeb-887def383812",
  "claveConfirmada": "12345"
}

###

GET https://localhost:8443/api/usuarios
Accept: application/json
Content-Type: */*
Authorization: {{auth_token}}
###

POST https://localhost:8443/api/usuarios
Accept: application/json
Content-Type: application/json

{
  "nombreUsuario": "prueba",
  "clave": "12345",
  "nombre": "Usuario de Prueba",
  "email": "usuario@test.com",
  "pasoActual": null,
  "estado": "ACTIVO",
  "intentos": 0,
  "roles": [],
  "id": "2f119690-96fe-4336-aeeb-887def383812",
  "claveConfirmada": "12345"
}

###
